
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: valentine
  password: 123

development:
  <<: *default
  database: WebChat_development

test:
  <<: *default
  database: WebChat_test


production:
  <<: *default
  database: WebChat_production

